apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/rewrite-target":"/"},"name":"voting-app-ingress","namespace":"blue"},"spec":{"ingressClassName":"nginx","rules":[{"host":"voting.104.208.125.89.nip.io","http":{"paths":[{"backend":{"service":{"name":"myapp-service","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}},{"host":"result.104.208.125.89.nip.io","http":{"paths":[{"backend":{"service":{"name":"result-app","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
      nginx.ingress.kubernetes.io/rewrite-target: /
    creationTimestamp: "2025-12-10T21:50:41Z"
    generation: 1
    name: voting-app-ingress
    namespace: blue
    resourceVersion: "88987"
    uid: 9acc2882-fe3b-4533-bf1f-01f3168172c7
  spec:
    ingressClassName: nginx
    rules:
    - host: voting.104.208.125.89.nip.io
      http:
        paths:
        - backend:
            service:
              name: myapp-service
              port:
                number: 80
          path: /
          pathType: Prefix
    - host: result.104.208.125.89.nip.io
      http:
        paths:
        - backend:
            service:
              name: result-app
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - ip: 104.208.125.89
kind: List
metadata:
  resourceVersion: ""
