apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: blue
spec:
  type: ClusterIP
  selector:
    app: voting-app
  ports:
    - port: 80
      targetPort: 80
#      nodePort: 30080
