apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  namespace: green
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      imagePullSecrets:
        - name: acr-secret 
      nodeSelector:
            env: green 
      containers:
      - name: voting-app-container
        image: shan365.azurecr.io/voting-app:latest
        ports:
        - containerPort: 80
